messages:
  # Placeholders:
  # %player_display_name% - The players display name
  # %player_username% - The players username
  welcome-message:
    enabled: true
    content:
      - "<gray><st>                                                           <reset>"
      - ""
      - "          <bold><aqua>Your Minecraft Server"
      - "           <green>Welcome %player_display_name%!"
      - ""
      - "<gray><st>                                                           <reset>"
  join-message:
    enabled: true
    content: "<dark_gray>[<green>+<dark_gray>] <gray>%player_username% joined!"
  leave-message:
    enabled: true
    content: "<dark_gray>[<red>-<dark_gray>] <gray>%player_username% left!"

items:
  teleport-bow:
    name: "<green>Teleport Bow"
    enabled: true
    slot: 0
  pvp-sword:
    name: "<dark_purple>PVP Sword"
    enabled: true
    slot: 4
    messages:
      # %time% - The time until the action will be executed
      prefix: "<white>[<aqua>PVP<white>] "
      enabling: "<aqua>Activating in <white>%time%s"
      enabled: "<green>Activated!"
      disabling: "<aqua>Will be deactivated in <white>%time%s"
      disabled: "<red>Deactivated!"
  player-visibility:
    name-shown: "<green>Hide Players"
    name-hidden: "<gray>Show Players"
    enabled: true
    slot: 7
  server-info:
    name: "<aqua>Server Info <gray>(Hover)"
    enabled: true
    slot: 8
    lore:
      - "Line 1"
      - "Line 2"

# dropItems, blockBreak, blockPlace and blockInteract will be ignored for player
# with the permission "crumblobby.admin (default: op)"
game-rules:
  dropItems: false
  pvp: false
  fallDamage: false
  fireDamage: false
  suffocate: false
  drown: false
  hunger: false
  blockBreak: false
  blockPlace: false
  blockInteract: false
