name: Crumb-Lobby
version: '1.0.6'
main: me.kalbskinder.crumbLobby.CrumbLobby
api-version: '26.2'
description: ""
author: "Kalbskinder"

permissions:
  crumblobby.admin:
    description: "Provides access to all plugin commands"
    default: op