name: Crumb-Lobby
version: '1.0.4'
main: me.kalbskinder.crumbLobby.CrumbLobby
api-version: '1.21'
description: ""
author: "Kalbskinder"

permissions:
  crumblobby.admin:
    description: "Provides access to all plugin commands"
    default: op