name: Crumb-Lobby
version: '1.0.5'
main: me.kalbskinder.crumbLobby.CrumbLobby
api-version: '26.1'
description: ""
author: "Kalbskinder"

permissions:
  crumblobby.admin:
    description: "Provides access to all plugin commands"
    default: op